#!/usr/bin/env scons
#
# To run things, do "scons  --clusters=prod  -j 123 --seeds=1" or
# for local "scons  --clusters=local  -j 123 --seeds=1"
#

import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest
import SCons.Script as sc

# Command line options

sc.AddOption('--seeds', type='int', help="SEEDS", default=1)
sc.AddOption('--output', type='string', help="output folder", default='_output')
# Or set this to --cluster=cluster
sc.AddOption('--cluster', type='string', help="cluster?", default='local')

env = sc.Environment(
        ENV=os.environ,
        num_seeds=sc.GetOption('seeds'),
        output=sc.GetOption('output'),
        cluster=sc.GetOption('cluster'))

sc.Export('env')

env.SConsignFile()

flag = 'simulation_adversary'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_improve'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_prespec_alignment'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_calib_auc'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'experiment_eicu'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'experiment_rsna'
sc.SConscript(flag + '/sconscript', exports=['flag'])
