---
title: "ICU data"
output: html_notebook
---
```{r}
library(ranger)
library(ROCit)
```


```{r}
head(eicu_hypotension_data)
```

```{r}
eicu_hypotension_data$`unified.map_16-predict` < 65
eicu_hypotension_data$`heartrate_1-obs`
eicu_hypotension_data$`respiration_1-obs`
eicu_hypotension_data$admissionheight
eicu_hypotension_data$window_offset[eicu_hypotension_data$patientunitstayid == 1001397]
```


```{r}
eicu_hypotension_new <- data.frame(
  patientunitstayid = eicu_hypotension_data$patientunitstayid,
  window_offset = eicu_hypotension_data$window_offset,
  # eicu_hypotension_data$male,
  # eicu_hypotension_data$age,
  # eicu_hypotension_data$admissionheight,
  # eicu_hypotension_data$admissionweight,
  eicu_hypotension_data$`unified.map_1-obs`,
  eicu_hypotension_data$`unified.map_2-obs`,
  # eicu_hypotension_data$`heartrate_1-obs`,
  # eicu_hypotension_data$`heartrate_2-obs`,
  # eicu_hypotension_data$`respiration_1-obs`,
  # eicu_hypotension_data$`respiration_2-obs`,
  # eicu_hypotension_data$`unified.map_3-obs`,
  # eicu_hypotension_data$`unified.map_4-obs`,
  # eicu_hypotension_data$`unified.map_5-obs`,
  # #eicu_hypotension_data$`unified.map_6-obs`,
  #eicu_hypotension_data$`unified.map_7-obs`,
  #eicu_hypotension_data$`unified.map_8-obs`,
  #eicu_hypotension_data$`unified.map_9-obs`,
  #eicu_hypotension_data$`unified.map_10-obs`,
  y=as.numeric(eicu_hypotension_data$`unified.map_16-predict` < 65)
)
eicu_hypotension_new <- eicu_hypotension_new[complete.cases(eicu_hypotension_new),]

eicu_hypotension_new <- eicu_hypotension_new[eicu_hypotension_new$window_offset <= 24 * 60,]

eicu_hypotension_new <- eicu_hypotension_new[order(eicu_hypotension_new$patientunitstayid, eicu_hypotension_new$window_offset),]

```

```{r}
# nrow(eicu_hypotension_new)
length(unique(eicu_hypotension_new$patientunitstayid))
write.csv(eicu_hypotension_new, "../../data/eicu_hypotension_data.csv", row.names = F)
```

```{r}
train_idx <- sample(1:nrow(eicu_hypotension_data), nrow(eicu_hypotension_data) * 0.5, replace = F)
train_dat <- eicu_hypotension_data[train_idx,]
test_dat <- eicu_hypotension_data[-train_idx,]
```

```{r}
danger_stays = unique(eicu_hypotension_new$patientunitstayid[eicu_hypotension_new$y == 1])
length(danger_stays)
eicu_hypotension_new$y[eicu_hypotension_new$patientunitstayid == danger_stays[30]]

table(eicu_hypotension_new$patientunitstayid)

stay_id = danger_stays[30]
train_dat <- eicu_hypotension_new[eicu_hypotension_new$patientunitstayid != stay_id,seq(3,ncol(eicu_hypotension_new))]
test_dat <- eicu_hypotension_new[eicu_hypotension_new$patientunitstayid == stay_id,seq(3,ncol(eicu_hypotension_new))]
```

```{r}
library(ranger)
rf_res <- ranger(y ~ ., train_dat, probability = T)
```

```{r}
library(ROCit)
rf_pred <- predict(rf_res, test_dat)$prediction
roc_res <- rocit(score = rf_pred[,2], class = test_dat$y)
summary(roc_res)
```

